apiVersion: v1
kind: Pod
metadata:
  name: redis-app-main-pod
  labels:
    name: redis-app-pod
    apptype: demo-voting-app
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
