apiVersion: v1
kind: Pod
metadata:
  name: result-app-main-pod
  labels:
    name: result-app-pod
    apptype: demo-voting-app
spec:
  containers:
  - name: result-app-container
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort: 80
