apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: user-result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: result-app-pod
    apptype: demo-voting-app
