apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-frontend
  labels:
    name: result-frontend
    env: demo-voting-app
spec:
  selector:
    matchLabels:
      name: result-app-pod
  template:
    metadata:
      name: result-app-main-pod
      labels:
        name: result-app-pod
        apptype: demo-voting-app
    spec:
      containers:
      - name: result-app-container
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
  replicas: 1
