apiVersion: v1
kind: Service
metadata:
  name: voteapp-service
  labels:
    name: user-vote-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: voting-app-pod
    apptype: demo-voting-app
