apiVersion: v1
kind: Pod
metadata:
  name: voting-app-main-pod
  labels:
    name: voting-app-pod
    apptype: demo-voting-app
spec:
  containers:
  - name: voting-app-container
    image: kodekloud/examplevotingapp_vote:v1
    ports:
    - containerPort: 80
