apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-frontend
  labels:
    apptype: frontend
    env: demo-voting-app
spec:
  selector:
    matchLabels:
      name: voting-app-pod
  template:
    metadata:
      name: voting-app-main-pod
      labels:
        name: voting-app-pod
        apptype: demo-voting-app
    spec:
      containers:
      - name: voting-app-container
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
  replicas: 1
